services:
  - type: web
    name: archivechain-backend
    env: node
    region: oregon
    plan: free
    buildCommand: cd backend && npm install --include=dev && npm run build
    startCommand: cd backend && npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 4000
      - key: GROQ_API_KEY
        sync: false
      - key: SUI_PACKAGE_ID
        sync: false
      - key: SUI_REGISTRY_ID
        sync: false
      - key: SUI_PRIVATE_KEY
        sync: false
      - key: TUSKY_API_KEY
        sync: false
      - key: SUI_RPC_URL
        value: https://fullnode.testnet.sui.io:443
